name: Pullrequest Workflow
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    if: github.repository == 'mirkosertic/flight-recorder-starter'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [11,12,13,14]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: ./mvnw verify
